import styles from "@/app/[...markdown]/markdown.module.css";
import { AbcPlayer, Abc, AbcMidiLink } from "@/components/abc";
import Toggle from "@/components/Toggle";


export default function JSPlaygroundPage() {
  return (
    <div className="container mx-auto px-4 py-8 max-w-4xl">
      <div className={styles.markdownContent}>
        <h1>Assignment 7: Music Generation Research</h1>
        <p>
          For this assignment, I chose Moises’s AI Studio.
          I selected it because I’ve used their stem-separation features before, 
          but I’ve never had the chance to try their AI DAW functionality. 
          Moises offers three subscription plans: Free, Premium, and Pro. 
          Since I currently have the Premium plan, I still have some limitations with the AI Studio features (for example, I can’t export the AI mixing results).
        </p>
        <p>
          Moises AI Studio is an AI-powered music creation platform that works in a web browser and on desktop.
          There are 4 key features.
        </p>

        <h5>
          1. AI Stem Generation
        </h5>
        <p>
          You can enerate new instrumental stems based on your existing recording
        </p>

        <h5>
          2. Stem Separation
        </h5>
        <p>
        You can further break stems down (e.g. separate different drum parts.)
        </p>

        <h5>
          3. Voice Conversion
        </h5>
        <p>
        You can pick a voice model from 40+ AI voice models, and convert your vocals or melody to that voice.
        </p>

        <h5>
          4. AI Mixing & Mastering
        </h5>
        <p>
        You can pick a genre preset and let AI mix your stems. They also have three AI mastering modes.
        </p>

        <h2>Audio Examples generated by Moises AI Studio</h2>

        <h3>Original Audio (Piano Solo)</h3>
        <img src="/students/fumiya/Screenshot 1.png" alt="AI Studio screenshot" className="rounded-lg shadow-lg w-220 mx-auto" />
        <audio src="/students/fumiya/25.05.06_Arthour_Piano Solo_T09.2.mp3" controls />

        <h3>AI Match Bass</h3>
        <audio src="/students/fumiya/HW7 - +Bass.mp3" controls />

        <h3>Convert Bass into Voice</h3>
             <img src="/students/fumiya/Screenshot 2.png" alt="AI Studio screenshot" className="rounded-lg shadow-lg w-220 mx-auto" />
        <audio src="/students/fumiya/HW7 - Bass Voice.mp3" controls />

        <h3>AI-Generated Hip-Hop Bass</h3>
        <audio src="/students/fumiya/HW7 - Hiphop Bass.mp3" controls />

        <h3>AI-Generated Upright Acoustic Bass</h3>
        <audio src="/students/fumiya/HW7 - Upright Acoustic Bass.mp3" controls />

       <h3>AI Match Guitar</h3>
        <audio src="/students/fumiya/HW7 - AI Match Guitar.mp3" controls />

       <h3>AI-Generated Solo Guitar</h3>
        <audio src="/students/fumiya/HW7 - GTR Solo.mp3" controls />

        <h3>AI-Generated Strings</h3>
        <audio src="/students/fumiya/HW7 - Strings.mp3" controls />

        <h3>AI Custom Generate Strings 1</h3>
        <img src="/students/fumiya/Screenshot 3.png" alt="AI Studio screenshot" className="rounded-lg shadow-lg w-220 mx-auto" />
        <audio src="/students/fumiya/HW7 - Custom Strings 1.mp3" controls />

        <h3>AI Custom Generate Strings 2</h3>
        <img src="/students/fumiya/Screenshot 4.png" alt="AI Studio screenshot" className="rounded-lg shadow-lg w-220 mx-auto" />
        <audio src="/students/fumiya/HW7 - Custom Strings 2.mp3" controls />

        <h3>AI-Generated Violin Solo</h3>
        <audio src="/students/fumiya/HW7 - Violin Solo.mp3" controls />

        <h3>AI Match Drum</h3>
        <audio src="/students/fumiya/HW7 - Drums.mp3" controls />

        <h3>AI-Generated Drum & Bass Drums</h3>
        <audio src="/students/fumiya/HW7 - D&B drums.mp3" controls />

        <h3>AI-Generated Jazz Drums</h3>
        <audio src="/students/fumiya/HW7 - Jazz Drums.mp3" controls />

      <h2>Reflection</h2>
        <p>
          While I found it very interesting to use, I feel there are still many limitations 
          that make it difficult to use practically in typical music composition. 
          The stem-generation feature is a powerful tool for expressing musical ideas 
          without needing to play an instrument. 
          However, the results still have a somewhat artificial quality, 
          which makes them less suitable for use in a final recording. 
          That said, it can be a very useful tool for developing demos in the early stages of the composition process.
        </p>
        <p>
          One feature I wish they offered is the ability to edit individual notes.
          Moises AI allows you to re-generate only a selected section, but it would be even more useful 
          if I could make more precise changes—such as adjusting a single note to a specific pitch.
        </p>
        <p>
          Before using an AI DAW for the first time, I didn’t really understand what it was 
          and even felt somewhat opposed to the idea. However, after this experiment, 
          my understanding of AI DAWs has deepened, and I can now imagine more people using AI stem-generation tools in the future. 
          Just as many music producers incorporate Splice samples into their compositions, 
          once these AI models advance enough to produce more authentic and musically pleasing sounds,
          I think AI-generated stems will become a common part of the creative process.
        </p>

      </div>
    </div>
  );
}

function GenerationObservations({
  title,
  period,
  composer,
  instrumentation,
  abcScore,
  observations,
}) {
  return (
    <div>
      <h3>{title}</h3>
      <div>Model Prompt:</div>
      <ul>
        <li>Period: {period}</li>
        <li>Composer: {composer}</li>
        <li>Instrumentation: {instrumentation}</li>
      </ul>
      <AbcPlayer abc={abcScore} hideScore={true} />
      <AbcMidiLink abc={abcScore} />
      <Toggle title="View Score">
        <Abc abc={abcScore} />
      </Toggle>
    </div>
  );
}

function TODO() {
  return <span className="text-red-500 font-bold">TODO</span>
}
